#!/bin/sh

## hyphop ##
for DOC in lev/album/Lev_Lapkin_6_year_kid_model; do

DATE=`TZ='UTC' date`
echo "[DATE] $DATE $DOC"

TITLE=`NOW=$DATE TITLE_OUT=1 tools/md2html $DOC.md $DOC.html`
echo "[T] $TITLE";

PDF=$DOC.pdf

echo "[PDF] $PDF";
#exit 
wkhtmltopdf --title "$TITLE" $DOC.html $PDF || \
    xvfb-run -- wkhtmltopdf wkhtmltopdf --title "$TITLE" $DOC.html $PDF

done