#!/usr/bin/perl

use common::sense;

## hyphop ##

#https://photos.app.goo.gl/VWQ63ZYhNPAA6Maq8
our $mode;

sub WIKI(){ 1 }
sub HTML(){ 2 }

our $BGI= "#fff";

our $img_num=0;
our $img_width='';
our $img_height='';

my $Hm;
my $Wi;

sub parse_{
    if ( /\[\"(.+?)\"\,\[\"(.+?)\",(\d+),(\d+)/ ) {
#	warn "[i] $2 - $3 x $4";
	    my $w = $3*1;
	    my $h = $4*1;
	    my $a = $w/$h;
	    my $A = $h/$w;

	    my $H = int($img_width * $A);
	    my $W = int($img_width * $a);

	    my $WW='';
	    $WW = "=w$W" if ($img_width);

	    $Wi = $W if $H > $Hm;
	    $Hm = $H if $H > $Hm;

	    $Wi=$img_width;


	if ( $mode == WIKI ) {
	    print "![$img_num]($2$W)\n";
	    $img_num++;
	    return
	}

	if ( $mode == HTML ) {
	    print qq{<a class="aitm" style="width: ${Wi}; height: ${Hm};" href="$2=w$w" target="_big">
<img alt="$img_num" src="$2$WW" style=""/>
</a>
};
	    $img_num++;
	    return
	}
	print "$2\n";
    }
}

sub get_{
    my $bytes;
    warn "[i] download $_[0]";
    my $r = open F, "-|", qw/curl -L -s/, $_[0];
    return undef unless $r;

    print qq{
<a href="$_[0]" target=_album>$_[0]</a>
};

    print qq{<style>
	.aitm{
	    float: left;
	    background: $BGI;
	    display: block;
	    padding: 4px;
	    min-height: 10em;
	    border: 0px solid #a00;
	}
	.albm{
	    min-height: 10em;
	    margin-left: auto;
	    margin-right: auto;
	    display: table-cell;
	    vertical-align: middle;
	    horizontal-align: middle;
	    align-items: center;
	    justify-content: center
	    display: block;
    	    background: $BGI;
	    border: 0px solid $BGI;
	}
</style>
<div class="albm">
};

    while (<F>){
	#parse_($_);
	$bytes+=length $_;
	&{$_[2]}($_)
    }

print qq{
    </div>
};

#    while 

}

my @SRC;
my @FILES;
my @args;


for (@ARGV) {
    if (/^http/ ) {
	push @SRC => $_;
	next;
    }
    if ( -s $_ ) { 
	push @FILES, $_;
	next;
    }
    push @args, $_;
}

for (0..$#args) {
#    warn "[arg] $_ : $args[$_]\n";
    if ( $args[$_] eq '-W' ) {
	$img_width=$args[$_+1];
    }
    if ( $args[$_] eq '-x' ) {
	$mode = HTML;
	if ( $args[$_+1] =~ /^\d+$/ ) {
	    $img_width=$args[$_+1];
	}
    }
    if ( $args[$_] eq '-w' ) {
	$mode = WIKI;
	if ( $args[$_+1] =~ /^\d+$/ ) {
	    $img_width=$args[$_+1];
	}
    }
}

warn "[i] args: @args // MODE: $mode\n";
warn "[i] src: @SRC + @FILES\n";

for (@SRC) {
    my $c;
    my $l = get_($_ => \$c => \&parse_);
    warn "[i] downloader $_ $l bytes\n";
}

#while (<>){
#    warn "[i] $_";
#}
__END__

["AF1QipPWDAw1cDOe963NMQ0pbY7fPH6-3Ke0mgjP5Y7Y",["https://lh3.googleusercontent.com/J71tB0HA8g2koR0OwJvazA5yOqz_iwtf1xFPyQ70gqH8qX_c-HFuSWcx_ftOpaFdSR3eMTqX-8ROs_UKUhVPASkaH4NI_CaZARUYzkLidC6CZCRqX3SpT9b2jgrjFMe7x3QNNswRIA",720,1280,null,null,null,null,null,null,[8092278]

