#!/usr/bin/perl

## hyphop ##

BEGIN {
    our $f = __FILE__;
    $f =~ s{^\.\/}{$ENV{PWD}/};
    $f = readlink $f if -l $f;
    $f =~ m{[^\/]+$};
    our $CWD = $`;
    unshift @INC, $CWD;
}

use Text::Markdown;
use Text::MultiMarkdown;

#our $m = Text::Markdown->new;
our $m = Text::MultiMarkdown->new(
    heading_ids => 0,
    img_ids => 0,
    );

exit unless @ARGV;

our $in = shift // "<&STDIN";
our $out = shift // ">&STDOUT";

warn "<$in> $out\n";

sub cat {
    `cat @_`
}

sub savefile {
    my $f;
    my $r = open $f, ">$_[1]";
    return undef unless $r;
    my $l = length $_[0];
    $r = syswrite $f, $_[0], $l;
    warn "[i] save $_[1] $l bytes\n";
    return $r;
}

$_ = cat $in;

$ENV{TITLE}//=$1 if m{#{1,}\s(.+)\n};

warn "[TITLE] $ENV{TITLE}\n";

our $TITLE_SAFE=$ENV{TITLE};

$TITLE_SAFE=~ s/\W+/_/g;
$TITLE_SAFE=~ s/_$//g;
$TITLE_SAFE=~ s/^_//g;

print $TITLE_SAFE if $ENV{TITLE_OUT};

#https://photos.app.goo.gl/VWQ63ZYhNPAA6Maq8 -W 120

sub galbum2{
    warn "# $CWD/galbum2 @_";
    "<!-- #galbum2#@_ -->\n"
    .
    `$CWD/galbum2 @_`
    .
    "<!-- #galbum2# -->\n"
}



sub youemb{
    warn "# youtube emb @_";
    qq{<iframe height="420" $4 src="$1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>}
}

s{\!\!(http(s?)://(www.)?youtu\S+)(.*?)\n}{youemb("$1","$4")}egi;

s{\b(http(s?)://\S+/(\S+\.(rar|xz|list)))}{[$3]($1)}sgi;
s{(?<=\s)((\S+)\@(\S+)\.(\w+))}{<a class="stopspam" href="mailto:$2(at)$3(dot)$4">$2(at)$3(dot)$4</a>}sgi;

our $LINKS='';

s{\B(\[\w+\]\:\s.+?\n)}{$LINKS.=$1;''}egi;

#s{\!\!(http(s?)://photos\S+\s+)(\-w[^<\n]+)}{galbum2("$1","$3")}egi;

s{(?<=\s)(http(s?)://\S+)}{[$1]($1)}sgi;

#s{(\b)(http(s?)://\S+)}{<a href="$1">$1</a>}sgi;


our %names;

sub getnamelink{
    my $name = lc $_[0];
    $name =~ s/\W/_/sg;
    $name =~ s/_+/_/sg;
    $name =~ s/_$//sg;
    my $n = $name;
    my $i=1;
    while ( $names{$name} ) {
	$name = $n . '_'. $i++;
    }
    $names{$name} = 1;
    warn "[NAME] $name\n";
    "<a name='$name'></a>"
}

s{(\#{2,5}\s+)([^\n]+)}{$1 . getnamelink($2) . $2 }esgi;

#warn "$LINKS";

$_ = $m->markdown($_.$LINKS);

s{\!\!(http(s?)://photos\S+\s+)(\-x|[^<\n]+)}{galbum2("$1","$3")}egi;
s{\!\!(http(s?)://photos\S+\s+)(\-z|[^<\n]+)}{galbum2("$1","$3")}egi;

$_ = cat("$CWD/../tpl/.html.header")
. $_ .
cat("$CWD/../tpl/.html.footer");


$_ =~ s{%%(\w+)%%}{$ENV{$1}}sgi;

savefile $_ => $out;

